import type { TransactionPayment } from './transactionPayment'
import type { GoalTransferKind } from './goal'

export type TransactionType = 'expense' | 'income' | 'reimbursement'

// Where the money for an expense came from - see
// docs/adr/003-installments-and-savings-funding.md.
export type FundingSource = 'income' | 'savings'

export interface Transaction {
  id: string
  user_id: string
  description: string
  amount: number
  type: TransactionType
  category_id: string | null
  date: string
  notes: string | null
  created_at: string | null
  /** 1 for a single payment; more for a purchase financed in monthly installments. */
  installment_months: number
  funding_source: FundingSource
  /**
   * For a reimbursement, the purchase it refunds; null when standalone and for
   * every other type. See docs/adr/006-reimbursement-purchase-links.md.
   */
  refunds_transaction_id: string | null
  /** Generated by the database from date + installment_months. */
  last_installment_date: string
  /** Present exactly when funding_source is 'savings'. */
  goal_transfer: TransactionGoalTransfer | null
  payments: TransactionPayment[]
}

// The Goal transfer tied to this transaction: a 'withdrawal' for a
// savings-funded expense (the full amount, on the expense's date - see
// docs/adr/004-goal-transfers.md), or a 'refund' for a reimbursement linked to
// one (see docs/adr/006-reimbursement-purchase-links.md). transaction_id is
// unique, so there is at most one.
export interface TransactionGoalTransfer {
  kind: GoalTransferKind
  goal_id: string
  amount: number
  goal: { name: string } | null
}

export const PAYMENT_METHODS = ['Credit Card', 'Debit Card', 'Cash', 'Bank Transfer', 'Grocery Vouchers']

/**
 * The method that received the largest share of a transaction, used to
 * consolidate legacy income/reimbursement rows that were split across several
 * methods into one. Ties go to the first payment recorded; `''` when there are
 * no payments.
 */
export function getPrimaryPaymentMethod(payments: Pick<TransactionPayment, 'payment_method' | 'amount'>[]): string {
  let primary: Pick<TransactionPayment, 'payment_method' | 'amount'> | null = null

  for (const payment of payments) {
    if (!primary || payment.amount > primary.amount) primary = payment
  }

  return primary?.payment_method ?? ''
}
