import type { TransactionPayment } from './transactionPayment'

export type TransactionType = 'expense' | 'income' | 'reimbursement'

// Where the money for an expense came from - see
// docs/adr/003-installments-and-savings-funding.md.
export type FundingSource = 'income' | 'savings'

export interface Transaction {
  id: string
  user_id: string
  description: string
  amount: number
  type: TransactionType
  category_id: string | null
  date: string
  notes: string | null
  created_at: string | null
  /** 1 for a single payment; more for a purchase financed in monthly installments. */
  installment_months: number
  funding_source: FundingSource
  /** Generated by the database from date + installment_months. */
  last_installment_date: string
  /** Present exactly when funding_source is 'savings'. */
  withdrawal: TransactionWithdrawal | null
  payments: TransactionPayment[]
}

// The Goal withdrawal covering a savings-funded expense - see
// docs/adr/004-goal-transfers.md. Always the full amount, on the expense's date.
export interface TransactionWithdrawal {
  goal_id: string
  amount: number
  goal: { name: string } | null
}

export const PAYMENT_METHODS = ['Credit Card', 'Debit Card', 'Cash', 'Bank Transfer', 'Grocery Vouchers']

/**
 * The method that received the largest share of a transaction, used to
 * consolidate legacy income/reimbursement rows that were split across several
 * methods into one. Ties go to the first payment recorded; `''` when there are
 * no payments.
 */
export function getPrimaryPaymentMethod(payments: Pick<TransactionPayment, 'payment_method' | 'amount'>[]): string {
  let primary: Pick<TransactionPayment, 'payment_method' | 'amount'> | null = null

  for (const payment of payments) {
    if (!primary || payment.amount > primary.amount) primary = payment
  }

  return primary?.payment_method ?? ''
}
